name: CI

on:
  push:
    branches:[develop]
  pull_request:
    branches:[develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: echo"Add your build/test commands here"